name: CI/CD DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install DigitalOcean CLI (doctl)
        run: sudo snap install doctl

      - name: Setup DigitalOcean API Token
        run: |
          if [[ -z "${{ secrets.DOCR_ACCESS_TOKEN }}" ]]; then
            echo "ERROR: DOCR_ACCESS_TOKEN is empty. Please set it in GitHub Secrets."
            exit 1
          fi
          doctl auth init --access-token ${{ secrets.DOCR_ACCESS_TOKEN }}

      - name: Login ke DigitalOcean Registry (DOCR)
        run: echo "${{ secrets.DOCR_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DOCR_USERNAME }} --password-stdin

      - name: Build dan Push Image ke DOCR
        run: |
          docker build -t registry.digitalocean.com/starterkit-reg-2/deployment:v1 .
          docker push registry.digitalocean.com/starterkit-reg-2/deployment:v1

      - name: Konfigurasi Kubernetes
        run: |
          mkdir -p /home/runner/.kube
          sudo snap connect doctl:kube-config
          doctl kubernetes cluster kubeconfig save starterkit-cluster-2

      - name: Deploy ke Kubernetes
        run: kubectl apply -f manifests/

      - name: Health Check - Verify Service Availability
        run: |
          kubectl get svc my-node-app-service --watch --timeout=2m
          kubectl get endpoints my-node-app-service
