name: CI/CD DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Install DigitalOcean CLI (doctl)
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-linux-amd64.tar.gz | tar -xz
          sudo mv doctl /usr/local/bin/

      - name: Login ke DigitalOcean CLI
        run: doctl auth init --access-token ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Login ke DigitalOcean Registry
        run: echo "${{ secrets.DOCR_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DOCR_USERNAME }} --password-stdin

      - name: Build dan Push Image ke DOCR
        run: |
          docker build -t registry.digitalocean.com/starterkit-reg-2/deployment:v1 .
          docker push registry.digitalocean.com/starterkit-reg-2/deployment:v1

      - name: Konfigurasi Kubernetes
        run: doctl kubernetes cluster kubeconfig save starterkit-cluster-2

      - name: Deploy ke Kubernetes
        run: kubectl apply -f manifests/
